## Provide a name in place of prometheus-operator for `app:` labels
nameOverride: "prometheus"

## Override the deployment namespace
namespaceOverride: "monitoring"

## Labels to apply to all resources
commonLabels: {}

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
alertmanager:
  ## Deploy alertmanager
  enabled: true

  ingress:
    enabled: true
    annotations:
       kubernetes.io/ingress.class: ingress-nginx
    hosts:
      - alertmanager.local

  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'

  ## Configuration for Alertmanager secret
  secret:
    annotations: {}

  ## Settings affecting alertmanagerSpec
  ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec
  alertmanagerSpec:
    ## Image of Alertmanager
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.21.0

    ## Secrets is a list of Secrets in the same namespace as the Alertmanager object, which shall be mounted into the
    ## Alertmanager Pods. The Secrets are mounted into /etc/alertmanager/secrets/.
    secrets: []

    ## ConfigMaps is a list of ConfigMaps in the same namespace as the Alertmanager object, which shall be mounted into the Alertmanager Pods.
    ## The ConfigMaps are mounted into /etc/alertmanager/configmaps/.
    configMaps: []

    ## ConfigSecret is the name of a Kubernetes Secret in the same namespace as the Alertmanager object, which contains configuration for
    ## this Alertmanager instance. Defaults to 'alertmanager-' The secret is mounted into /etc/alertmanager/config.
    # configSecret:

    ## Storage is the definition of how storage will be used by the Alertmanager instances.
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    storage: {}
    # volumeClaimTemplate:
    #   spec:
    #     storageClassName: gluster
    #     accessModes: ["ReadWriteOnce"]
    #     resources:
    #       requests:
    #         storage: 50Gi
    #   selector: {}

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: prom-operator

  ingress:
    enabled: true
    annotations:
       kubernetes.io/ingress.class: ingress-nginx
    hosts:
       - grafana.local

prometheus:
  enabled: true
  ingress:
    enabled: true
    annotations:
       kubernetes.io/ingress.class: ingress-nginx
    hosts:
       - prometheus.local

  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false

    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false

    ruleSelector: {}
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false


